<?php
echo "\\其他类型转换成数值型";
echo 1+true;
echo "<hr />";
echo 1+FALSE;
echo "<hr />";
echo 1.2+true;
echo "<hr />";
echo 1+null;
echo "<hr />";
echo 1+'a';
echo "<hr />";
echo 1+"true";
echo '<hr />';
echo 1+"123king";
echo '<hr />';
echo 1+'3qu2e1nn4';
echo '<hr />';
echo 1+'3.2abc';
echo '<hr />';
echo 1+'-3e2aaa';
echo '\\其他类型转换成字符串型';
echo '<hr />';
echo 123;
echo '<hr />';
echo 12.3;
echo '<hr />';
echo true;
echo '<hr />';
echo false;
echo '<hr />';
echo null;
echo '<hr />';
$array=array();
echo $array;
$handle = fopen('string_5.php','r');
echo $handle;
echo '<hr />';
$object = new sdclass();
echo $object;
echo '\\其他类型转换成布尔型';